"""empty message

Revision ID: aba67cb9d070
Revises: 
Create Date: 2026-09-28 17:11:51.885511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba67cb9d070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_type_id', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id')
    )
    op.create_table('request_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('request_type_id')
    )
    op.create_table('shelter_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shelter_type_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelter_type_id')
    )
    op.create_table('animal_type_requirement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_type_requirement_id', sa.String(), nullable=False),
    sa.Column('animal_type_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_checked_by_default', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_requirement_id')
    )
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shelter_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('map_positioning', sa.String(), nullable=True),
    sa.Column('shelter_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shelter_type_id'], ['shelter_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('shelter_id')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('vaccines', sa.String(), nullable=True),
    sa.Column('has_microchip', sa.Boolean(), nullable=True),
    sa.Column('is_sterilized', sa.Boolean(), nullable=True),
    sa.Column('tests_done', sa.String(), nullable=True),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.Column('lives_with_kids', sa.Boolean(), nullable=True),
    sa.Column('lives_with_dogs', sa.Boolean(), nullable=True),
    sa.Column('lives_with_cats', sa.Boolean(), nullable=True),
    sa.Column('ideal_home', sa.Text(), nullable=True),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('animal_type_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_type.id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name1', sa.String(), nullable=False),
    sa.Column('last_name2', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('map_positioning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('addoption_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addoption_process_id', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('concurrent_requests_limit', sa.Integer(), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addoption_process_id')
    )
    op.create_table('animal_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_deadline', sa.DateTime(), nullable=True),
    sa.Column('amount_needed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('footnote', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_type.id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('user_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('addoption_process_requirement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addoption_process_requirement_id', sa.String(), nullable=False),
    sa.Column('addoption_process_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addoption_process_id'], ['addoption_process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addoption_process_requirement_id')
    )
    op.create_table('addoption_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addoption_request_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('addoption_process_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addoption_process_id'], ['addoption_process.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addoption_request_id')
    )
    op.create_table('addoption_request_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addoption_request_question_id', sa.String(), nullable=False),
    sa.Column('addoption_process_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addoption_process_id'], ['addoption_process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addoption_request_question_id')
    )
    op.create_table('request_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    op.create_table('user_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_request_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('shelter_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_request_id')
    )
    op.create_table('addoption_request_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addoption_request_answer_id', sa.String(), nullable=False),
    sa.Column('addoption_request_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addoption_request_id'], ['addoption_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addoption_request_answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addoption_request_answer')
    op.drop_table('user_request')
    op.drop_table('request_media')
    op.drop_table('addoption_request_question')
    op.drop_table('addoption_request')
    op.drop_table('addoption_process_requirement')
    op.drop_table('user_review')
    op.drop_table('request')
    op.drop_table('animal_media')
    op.drop_table('addoption_process')
    op.drop_table('user')
    op.drop_table('animal')
    op.drop_table('shelter')
    op.drop_table('animal_type_requirement')
    op.drop_table('shelter_type')
    op.drop_table('request_type')
    op.drop_table('animal_type')
    # ### end Alembic commands ###
